os: linux
dist: jammy
language: python
python:
  - "3.11"

cache: pip

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE=playground1.settings
    - PYTHONUNBUFFERED=1

script:
  - python manage.py test -v 2

branches:
  only:
    - main

deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $EB_APP_NAME
  env: $EB_ENV_NAME
  bucket: $EB_BUCKET
  on:
    branch: main
