branch-defaults:
  default:
    environment: rf2887-playground1-env
  main:
    environment: rf2887-playground1-env
environment-defaults:
  rf2887-playground1-env:
    branch: null
    repository: null
global:
  application_name: rf2887-swe-eb-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
